### ISSUE TITLE
save preferences to file and load them back

### ISSUE THREAD

**Issue by kolesar-andras** [sctg-development/RtkGps#39]
RTKLIB has a lot of settings. Solution quality depends on them. Fine-tuning real-time parameters in mobile device and postprocessing on desktop with same or slightly different settings needs an easy way to share settings.

**Comment by jancelin** [comment]
Hi,
 Well done for the updates.  Good work.
 I have also just made changes, especially on the RTKLIB side to benefit from the latest innovations, ublox F9P compatibility and a fast RTK fix (methose validated under Linux:
https://github.com/jancelin/RTKlibDroid)

 I manage to have the same precision with my patch on RTKGPS+ but only in TCP because I cannot activate the connection in USB ... Any idea?
 To work around the problem I use the TCPUART apk and there no problem (USB to TCP).
https://play.google.com/store/apps/details?id=com.hardcodedjoy.tcpuart&hl=fr

My Rtklib for RTKGPS+
https://github.com/jancelin/RTKLIB

 My settings are in my repository here.

https://github.com/jancelin/RtkGps/blob/master/settings1_RTK.png

https://github.com/jancelin/RtkGps/blob/master/settings2_RTK.png

https://github.com/jancelin/RtkGps

Thanks !
